stages:
  get_videos:
    cmd: python src/get_videos.py
    deps:
    - src/config.py
    outs:
    - data/videos
  extract_frames:
    cmd: python src/extract_frames.py
    deps:
    - data/videos
    - src/config.py
    - src/utils.py
    outs:
    - data/raw
